# Generated by Django 5.2.5 on 2025-09-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='generated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
